# Form implementation generated from reading ui file 'client_form.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ClientForm(object):
    def setupUi(self, ClientForm):
        ClientForm.setObjectName("ClientForm")
        ClientForm.resize(900, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(ClientForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchBar = QtWidgets.QHBoxLayout()
        self.searchBar.setObjectName("searchBar")
        self.search_label = QtWidgets.QLabel(parent=ClientForm)
        self.search_label.setObjectName("search_label")
        self.searchBar.addWidget(self.search_label)
        self.search_lineEdit = QtWidgets.QLineEdit(parent=ClientForm)
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.searchBar.addWidget(self.search_lineEdit)
        self.add_btn = QtWidgets.QPushButton(parent=ClientForm)
        self.add_btn.setObjectName("add_btn")
        self.searchBar.addWidget(self.add_btn)
        self.edit_btn = QtWidgets.QPushButton(parent=ClientForm)
        self.edit_btn.setObjectName("edit_btn")
        self.searchBar.addWidget(self.edit_btn)
        self.delete_btn = QtWidgets.QPushButton(parent=ClientForm)
        self.delete_btn.setObjectName("delete_btn")
        self.searchBar.addWidget(self.delete_btn)
        self.verticalLayout.addLayout(self.searchBar)
        self.client_table = QtWidgets.QTableView(parent=ClientForm)
        self.client_table.setObjectName("client_table")
        self.verticalLayout.addWidget(self.client_table)
        self.bottomBar = QtWidgets.QHBoxLayout()
        self.bottomBar.setObjectName("bottomBar")
        self.export_btn = QtWidgets.QPushButton(parent=ClientForm)
        self.export_btn.setObjectName("export_btn")
        self.bottomBar.addWidget(self.export_btn)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.bottomBar.addItem(spacerItem)
        self.close_btn = QtWidgets.QPushButton(parent=ClientForm)
        self.close_btn.setObjectName("close_btn")
        self.bottomBar.addWidget(self.close_btn)
        self.verticalLayout.addLayout(self.bottomBar)

        self.retranslateUi(ClientForm)
        QtCore.QMetaObject.connectSlotsByName(ClientForm)

    def retranslateUi(self, ClientForm):
        _translate = QtCore.QCoreApplication.translate
        ClientForm.setWindowTitle(_translate("ClientForm", "Справочник клиентов"))
        self.search_label.setText(_translate("ClientForm", "Поиск:"))
        self.search_lineEdit.setPlaceholderText(_translate("ClientForm", "Введите имя клиента..."))
        self.add_btn.setText(_translate("ClientForm", "Добавить"))
        self.edit_btn.setText(_translate("ClientForm", "Изменить"))
        self.delete_btn.setText(_translate("ClientForm", "Удалить"))
        self.export_btn.setText(_translate("ClientForm", "Экспорт CSV"))
        self.close_btn.setText(_translate("ClientForm", "Закрыть"))
