# Form implementation generated from reading ui file 'settings_form.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingsForm(object):
    def setupUi(self, SettingsForm):
        SettingsForm.setObjectName("SettingsForm")
        SettingsForm.resize(600, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.db_group = QtWidgets.QGroupBox(parent=SettingsForm)
        self.db_group.setObjectName("db_group")
        self.formLayout = QtWidgets.QFormLayout(self.db_group)
        self.formLayout.setObjectName("formLayout")
        self.host_label = QtWidgets.QLabel(parent=self.db_group)
        self.host_label.setObjectName("host_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.host_label)
        self.host_lineEdit = QtWidgets.QLineEdit(parent=self.db_group)
        self.host_lineEdit.setObjectName("host_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.host_lineEdit)
        self.user_label = QtWidgets.QLabel(parent=self.db_group)
        self.user_label.setObjectName("user_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.user_label)
        self.user_lineEdit = QtWidgets.QLineEdit(parent=self.db_group)
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.user_lineEdit)
        self.password_label = QtWidgets.QLabel(parent=self.db_group)
        self.password_label.setObjectName("password_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.password_label)
        self.password_lineEdit = QtWidgets.QLineEdit(parent=self.db_group)
        self.password_lineEdit.setEchoMode(QtCore.Qt.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.password_lineEdit)
        self.db_label = QtWidgets.QLabel(parent=self.db_group)
        self.db_label.setObjectName("db_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.db_label)
        self.db_lineEdit = QtWidgets.QLineEdit(parent=self.db_group)
        self.db_lineEdit.setObjectName("db_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.db_lineEdit)
        self.verticalLayout.addWidget(self.db_group)
        self.buttonBar = QtWidgets.QHBoxLayout()
        self.buttonBar.setObjectName("buttonBar")
        self.save_btn = QtWidgets.QPushButton(parent=SettingsForm)
        self.save_btn.setObjectName("save_btn")
        self.buttonBar.addWidget(self.save_btn)
        self.test_btn = QtWidgets.QPushButton(parent=SettingsForm)
        self.test_btn.setObjectName("test_btn")
        self.buttonBar.addWidget(self.test_btn)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.buttonBar.addItem(spacerItem)
        self.close_btn = QtWidgets.QPushButton(parent=SettingsForm)
        self.close_btn.setObjectName("close_btn")
        self.buttonBar.addWidget(self.close_btn)
        self.verticalLayout.addLayout(self.buttonBar)

        self.retranslateUi(SettingsForm)
        QtCore.QMetaObject.connectSlotsByName(SettingsForm)

    def retranslateUi(self, SettingsForm):
        _translate = QtCore.QCoreApplication.translate
        SettingsForm.setWindowTitle(_translate("SettingsForm", "Настройки"))
        self.db_group.setTitle(_translate("SettingsForm", "База данных"))
        self.host_label.setText(_translate("SettingsForm", "Хост:"))
        self.user_label.setText(_translate("SettingsForm", "Пользователь:"))
        self.password_label.setText(_translate("SettingsForm", "Пароль:"))
        self.db_label.setText(_translate("SettingsForm", "Имя базы:"))
        self.save_btn.setText(_translate("SettingsForm", "Сохранить"))
        self.test_btn.setText(_translate("SettingsForm", "Проверить соединение"))
        self.close_btn.setText(_translate("SettingsForm", "Закрыть"))
