# Form implementation generated from reading ui file 'login_form.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.login_label = QtWidgets.QLabel(parent=Dialog)
        self.login_label.setObjectName("login_label")
        self.gridLayout.addWidget(self.login_label, 0, 0, 1, 1)
        self.login_lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.login_lineEdit.setObjectName("login_lineEdit")
        self.gridLayout.addWidget(self.login_lineEdit, 0, 1, 1, 2)
        self.password_label = QtWidgets.QLabel(parent=Dialog)
        self.password_label.setObjectName("password_label")
        self.gridLayout.addWidget(self.password_label, 1, 0, 1, 1)
        self.password_lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.gridLayout.addWidget(self.password_lineEdit, 1, 1, 1, 2)
        self.enter_pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.enter_pushButton.setObjectName("enter_pushButton")
        self.gridLayout.addWidget(self.enter_pushButton, 2, 0, 1, 1)
        self.cancel_pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.gridLayout.addWidget(self.cancel_pushButton, 2, 1, 1, 1)
        self.register_pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.register_pushButton.setObjectName("register_pushButton")
        self.gridLayout.addWidget(self.register_pushButton, 2, 2, 1, 1)
        self.status_label = QtWidgets.QLabel(parent=Dialog)
        self.status_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.status_label.setObjectName("status_label")
        self.gridLayout.addWidget(self.status_label, 3, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Авторизация"))
        self.login_label.setText(_translate("Dialog", "Логин:"))
        self.password_label.setText(_translate("Dialog", "Пароль:"))
        self.enter_pushButton.setText(_translate("Dialog", "Войти"))
        self.cancel_pushButton.setText(_translate("Dialog", "Отмена"))
        self.register_pushButton.setText(_translate("Dialog", "Регистрация"))
        self.status_label.setText(_translate(
            "Dialog", "Неверный логин/пароль"))
