# Form implementation generated from reading ui file 'parts_form.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PartsForm(object):
    def setupUi(self, PartsForm):
        PartsForm.setObjectName("PartsForm")
        PartsForm.resize(900, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(PartsForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topBar = QtWidgets.QHBoxLayout()
        self.topBar.setObjectName("topBar")
        self.search_label = QtWidgets.QLabel(parent=PartsForm)
        self.search_label.setObjectName("search_label")
        self.topBar.addWidget(self.search_label)
        self.search_lineEdit = QtWidgets.QLineEdit(parent=PartsForm)
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.topBar.addWidget(self.search_lineEdit)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.topBar.addItem(spacerItem)
        self.import_btn = QtWidgets.QPushButton(parent=PartsForm)
        self.import_btn.setObjectName("import_btn")
        self.topBar.addWidget(self.import_btn)
        self.export_btn = QtWidgets.QPushButton(parent=PartsForm)
        self.export_btn.setObjectName("export_btn")
        self.topBar.addWidget(self.export_btn)
        self.verticalLayout.addLayout(self.topBar)
        self.mainLayout = QtWidgets.QHBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.parts_table = QtWidgets.QTableView(parent=PartsForm)
        self.parts_table.setSelectionBehavior(QtCore.Qt.QAbstractItemView.SelectRows)
        self.parts_table.setAlternatingRowColors(True)
        self.parts_table.setEditTriggers(QtCore.Qt.QAbstractItemView.NoEditTriggers)
        self.parts_table.setObjectName("parts_table")
        self.mainLayout.addWidget(self.parts_table)
        self.line = QtWidgets.QFrame(parent=PartsForm)
