# Form implementation generated from reading ui file 'register_form.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegisterDialog(object):
    def setupUi(self, RegisterDialog):
        RegisterDialog.setObjectName("RegisterDialog")
        RegisterDialog.resize(400, 250)
        self.gridLayout = QtWidgets.QGridLayout(RegisterDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.login_label = QtWidgets.QLabel(parent=RegisterDialog)
        self.login_label.setObjectName("login_label")
        self.gridLayout.addWidget(self.login_label, 0, 0, 1, 1)
        self.login_lineEdit = QtWidgets.QLineEdit(parent=RegisterDialog)
        self.login_lineEdit.setObjectName("login_lineEdit")
        self.gridLayout.addWidget(self.login_lineEdit, 0, 1, 1, 1)
        self.password_label = QtWidgets.QLabel(parent=RegisterDialog)
        self.password_label.setObjectName("password_label")
        self.gridLayout.addWidget(self.password_label, 1, 0, 1, 1)
        self.password_lineEdit = QtWidgets.QLineEdit(parent=RegisterDialog)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.gridLayout.addWidget(self.password_lineEdit, 1, 1, 1, 1)
        self.register_pushButton = QtWidgets.QPushButton(parent=RegisterDialog)
        self.register_pushButton.setObjectName("register_pushButton")
        self.gridLayout.addWidget(self.register_pushButton, 2, 0, 1, 1)
        self.cancel_pushButton = QtWidgets.QPushButton(parent=RegisterDialog)
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.gridLayout.addWidget(self.cancel_pushButton, 2, 1, 1, 1)
        self.status_label = QtWidgets.QLabel(parent=RegisterDialog)
        self.status_label.setText("")
        self.status_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.status_label.setObjectName("status_label")
        self.gridLayout.addWidget(self.status_label, 3, 0, 1, 2)

        self.retranslateUi(RegisterDialog)
        QtCore.QMetaObject.connectSlotsByName(RegisterDialog)

    def retranslateUi(self, RegisterDialog):
        _translate = QtCore.QCoreApplication.translate
        RegisterDialog.setWindowTitle(
            _translate("RegisterDialog", "Регистрация"))
        self.login_label.setText(_translate("RegisterDialog", "Логин:"))
        self.password_label.setText(_translate("RegisterDialog", "Пароль:"))
        self.register_pushButton.setText(
            _translate("RegisterDialog", "Создать"))
        self.cancel_pushButton.setText(_translate("RegisterDialog", "Отмена"))
