# Form implementation generated from reading ui file 'report_form.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ReportForm(object):
    def setupUi(self, ReportForm):
        ReportForm.setObjectName("ReportForm")
        ReportForm.resize(900, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(ReportForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filterBar = QtWidgets.QHBoxLayout()
        self.filterBar.setObjectName("filterBar")
        self.label = QtWidgets.QLabel(parent=ReportForm)
        self.label.setObjectName("label")
        self.filterBar.addWidget(self.label)
        self.date_from = QtWidgets.QDateEdit(parent=ReportForm)
        self.date_from.setCalendarPopup(True)
        self.date_from.setObjectName("date_from")
        self.filterBar.addWidget(self.date_from)
        self.label_to = QtWidgets.QLabel(parent=ReportForm)
        self.label_to.setObjectName("label_to")
        self.filterBar.addWidget(self.label_to)
        self.date_to = QtWidgets.QDateEdit(parent=ReportForm)
        self.date_to.setCalendarPopup(True)
        self.date_to.setObjectName("date_to")
        self.filterBar.addWidget(self.date_to)
        self.generate_btn = QtWidgets.QPushButton(parent=ReportForm)
        self.generate_btn.setObjectName("generate_btn")
        self.filterBar.addWidget(self.generate_btn)
        self.verticalLayout.addLayout(self.filterBar)
        self.report_table = QtWidgets.QTableView(parent=ReportForm)
        self.report_table.setObjectName("report_table")
        self.verticalLayout.addWidget(self.report_table)
        self.bottomBar = QtWidgets.QHBoxLayout()
        self.bottomBar.setObjectName("bottomBar")
        self.export_btn = QtWidgets.QPushButton(parent=ReportForm)
        self.export_btn.setObjectName("export_btn")
        self.bottomBar.addWidget(self.export_btn)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.bottomBar.addItem(spacerItem)
        self.close_btn = QtWidgets.QPushButton(parent=ReportForm)
        self.close_btn.setObjectName("close_btn")
        self.bottomBar.addWidget(self.close_btn)
        self.verticalLayout.addLayout(self.bottomBar)

        self.retranslateUi(ReportForm)
        QtCore.QMetaObject.connectSlotsByName(ReportForm)

    def retranslateUi(self, ReportForm):
        _translate = QtCore.QCoreApplication.translate
        ReportForm.setWindowTitle(_translate("ReportForm", "Отчеты"))
        self.label.setText(_translate("ReportForm", "Период:"))
        self.label_to.setText(_translate("ReportForm", "—"))
        self.generate_btn.setText(_translate("ReportForm", "Сформировать"))
        self.export_btn.setText(_translate("ReportForm", "Экспорт в Excel"))
        self.close_btn.setText(_translate("ReportForm", "Закрыть"))
